import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Playfair,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import IncomingCall from "@/components/incoming-call";
import Connection from "./chat/_components/connection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={
          {
            // backgroundColor: "#dab2ff",
          }
        }
      >
        {/* <Navbar /> */}
        <main>{children}</main>
        <IncomingCall />
        <Connection />
        <Toaster />
      </body>
    </html>
  );
}
